project/urls.py
# trade_project/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trades.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trades/urls.py
# trades/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.trade_list, name='trade_list'),
    path('trade/<int:pk>/', views.trade_detail, name='trade_detail'),
    path('trade/new/', views.add_trade, name='add_trade'),

    path('trade/<int:pk>/edit/', views.edit_trade, name='edit_trade'),
    path('trade/<int:pk>/delete/', views.delete_trade, name='delete_trade'),
]

trades/models.py
from django.db import models

class Trade(models.Model):
    TRADE_TYPES = [
        ('crypto_future', 'Crypto Future'),
        ('crypto_spot', 'Crypto Spot'),
        ('forex', 'Forex'),
    ]
    TRADE_DIRECTION_CHOICES = [
        ('Buy / Future', 'Buy / Future'),
        ('Short / Future', 'Short / Future'),
        ('Spot', 'Spot'),
    ]

    TIMEFRAME_CHOICES = [
        ('1 M', '1 Minute'),
        ('5 M', '5 Minutes'),
        ('15 M', '15 Minutes'),
        ('1 H', '1 Hour'),
        ('2 H', '2 Hours'),
        ('3 H', '3 Hours'),
        ('4 H', '4 Hours'),
        ('D', 'Daily'),
        ('W', 'Weekly'),
        ('M', 'Monthly'),
        ('Y', 'Yearly'),
    ]

    currency_fair = models.TextField(blank=True, null=True)

    open_date = models.DateField()
    open_time = models.TimeField()
    close_date = models.DateField()
    close_time = models.TimeField()
    
    # Trade Setup fields
    trade_type = models.CharField(max_length=20, choices=TRADE_TYPES, default='crypto_spot')
    action = models.CharField(max_length=15, choices=TRADE_DIRECTION_CHOICES)  # Updated max_length to 15
    time_frame = models.CharField(max_length=10, choices=TIMEFRAME_CHOICES)
    win_lose = models.CharField(max_length=5)
    margine = models.DecimalField(max_digits=10, decimal_places=2)
    leverage = models.CharField(max_length=20)
    sl = models.CharField(max_length=20)
    tp = models.CharField(max_length=100)
    open_price = models.CharField(max_length=20)
    risk_reward_ratio = models.DecimalField(max_digits=5, decimal_places=2)
    target_price = models.CharField(max_length=20)
    stop = models.CharField(max_length=20)
    close_price = models.CharField(max_length=20)
    duration = models.CharField(max_length=20)
    gain = models.CharField(max_length=10)
    profit_loss = models.CharField(max_length=20)
    
    # Market Analysis fields
    technical_analysis_charts_patterns = models.TextField()
    technical_analysis_indicators = models.TextField()
    volume_analysis = models.TextField()
    support_resistance = models.TextField()
    trend = models.CharField(max_length=10)
    fibonacci_retracement = models.TextField()
    smc_trading = models.TextField()
    fundamental_analysis = models.TextField()
    
    # Screen Shots fields
    entry_trade_image = models.ImageField(upload_to='photos/entry/', null=True, blank=True)
    exit_trade_image = models.ImageField(upload_to='photos/exit/', null=True, blank=True)
    technical_analysis_image = models.ImageField(upload_to='photos/technical/', null=True, blank=True)
    
    # Mistakes fields
    mistakes = models.JSONField(default=list, blank=True, null=True)
    
    # Lessons Learned fields
    lessons = models.JSONField(default=list, blank=True, null=True)
    
    # Additional fields
    additional = models.JSONField(default=list, blank=True, null=True)

    def __str__(self):
        return f"Trade {self.id} - {self.open_date} - {self.open_time} - {self.currency_fair}"

trades/forms.py
from django import forms
from .models import Trade

class TradeForm(forms.ModelForm):
    class Meta:
        model = Trade
        fields = '__all__'

trades/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Trade
from .forms import TradeForm

def trade_list(request):
    crypto_futures = Trade.objects.filter(trade_type='crypto_future')
    crypto_spot = Trade.objects.filter(trade_type='crypto_spot')
    forex = Trade.objects.filter(trade_type='forex')
    
    context = {
        'crypto_futures': crypto_futures,
        'crypto_spot': crypto_spot,
        'forex': forex,
    }
    
    return render(request, 'index.html', context)

def trade_detail(request, pk):
    trade = get_object_or_404(Trade, pk=pk)
    return render(request, 'trade_detail.html', {'trade': trade})

def add_trade(request):
    if request.method == "POST":
        form = TradeForm(request.POST, request.FILES)
        if form.is_valid():
            trade = form.save()
            return redirect('trade_detail', pk=trade.pk)
    else:
        form = TradeForm()
    return render(request, 'add_trade.html', {'form': form})

def edit_trade(request, pk):
    trade = get_object_or_404(Trade, pk=pk)
    if request.method == "POST":
        form = TradeForm(request.POST,  request.FILES, instance=trade)
        if form.is_valid():
            form.save()
            return redirect('trade_detail', pk=trade.pk)
    else:
        form = TradeForm(instance=trade)
    return render(request, 'trades/edit_trade.html', {'form': form})

def delete_trade(request, pk):
    trade = get_object_or_404(Trade, pk=pk)
    if request.method == "POST":
        trade.delete()
        return redirect('trade_list')
    return render(request, 'trades/confirm_delete.html', {'trade': trade})

trades/templates/add_trade.html
<!-- trades/templates/add_trade.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Add Trade</title>
</head>
<body>
    <h1>Add Trade</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'trade_list' %}">Back to Trade List</a>
</body>
</html>

trades/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Trade List</title>
    
</head>
<body>
    
    <h1>Trade List</h1>
    <a href="{% url 'add_trade' %}">Add New Trade</a>
    
    <section>
        <h2>Crypto Futures</h2>
        <ul>
            {% for trade in crypto_futures %}
                <li><a href="{% url 'trade_detail' trade.id %}">{{ trade }}</a></li>
            {% endfor %}
        </ul>
    </section>
    
    <section>
        <h2>Crypto Spot</h2>
        <ul>
            {% for trade in crypto_spot %}
                <li><a href="{% url 'trade_detail' trade.id %}">{{ trade }}</a></li>
            {% endfor %}
        </ul>
    </section>
    
    <section>
        <h2>Forex</h2>
        <ul>
            {% for trade in forex %}
                <li><a href="{% url 'trade_detail' trade.id %}">{{ trade }}</a></li>
            {% endfor %}
        </ul>
    </section>

    
</body>
</html>

trades/templates/trade_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Trade Detail</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="container1">


    <div class="container">
        <h1 class="title">{{ trade.currency_fair }}</h1>
        <div class="date-time">
            <p><strong>Open Date:</strong> {{ trade.open_date|date:"Y-m-d" }}</p>
            <p><strong>Open Time:</strong> {{ trade.open_time|time:"h:i A" }}</p>
            <p><strong>Close Date:</strong> {{ trade.close_date|date:"Y-m-d" }}</p>
            <p><strong>Open Time:</strong> {{ trade.close_time|time:"h:i A" }}</p>
        </div>
        <div class="trade-setup">
            <h2>Trade Setup</h2>
            <div class="setup-details">
                <div class="detail">
                    <p>Action</p>
                    <p>{{ trade.get_action_display }}</p>
                </div>
                <div class="detail">
                    <p>Time Frame</p>
                    <p>{{ trade.get_time_frame_display }}</p>
                </div>
                <div class="detail">
                    <p>Win/Lose</p>
                    <p>{{ trade.win_lose }}</p>
                </div>
                <div class="detail">
                    <p>Margin</p>
                    <p>{{ trade.margine }}</p>
                </div>
                <div class="detail">
                    <p>Leverage</p>
                    <p>{{ trade.leverage }}</p>
                </div>
                <div class="detail">
                    <p>SL</p>
                    <p>{{ trade.sl }}</p>
                </div>
                <div class="detail">
                    <p>TP</p>
                    <p>{{ trade.tp }}</p>
                    
                </div>
                <div class="detail">
                    <p>Open Price</p>
                    <p>{{ trade.open_price }}</p>
                </div>
                <div class="detail">
                    <p>Risk/Reward Ratio</p>
                    <p>{{ trade.risk_reward_ratio }}</p>
                </div>
                <div class="detail">
                    <p>Target Price</p>
                    <p>{{ trade.target_price }}</p>
                </div>
                <div class="detail">
                    <p>Stop</p>
                    <p>{{ trade.stop }}</p>
                </div>
                <div class="detail">
                    <p>Close Price</p>
                    <p>{{ trade.close_price }}</p>
                </div>
                <div class="detail">
                    <p>Duration</p>
                    <p>{{ trade.duration }}</p>
                </div>
                <div class="detail">
                    <p>Gain</p>
                    <p>{{ trade.gain }} %</p>
                </div>
                <div class="detail">
                    <p>Profit / Loss</p>
                    <p>{{ trade.profit_loss }}</p>
                </div>
            </div>
        </div>

        
    </div>
    <div class="container">
    <div class="market-analysis">
        <h2>Market Analysis</h2>
        <div class="technical-analysis">
            <h3>Technical Analysis</h3>
            <div class="analysis-section">
                <p><strong>Technical Analysis Charts/Patterns:</strong> </p>
                <p>{{ trade.technical_analysis_charts_patterns }}</p>
            </div>
            <div class="analysis-section">
                <p><strong>Technical Analysis Indicators:</strong></p>
                <p>{{ trade.technical_analysis_indicators }}</p>
            </div>
            <div class="analysis-section">
                <p><strong>Volume Analysis:</strong></p>
                <p>{{ trade.volume_analysis }}</p>
            </div>
            <div class="analysis-section">
                <p><strong>Support/Resistance:</strong></p>
                <p>{{ trade.support_resistance }}</p>
            </div>
            <div class="analysis-section">
                <p><strong>Trend:</strong></p>
                <p>{{ trade.trend }}</p>
            </div>
            <div class="analysis-section">
                <p><strong>Fibonacci Retracement:</strong></p>
                <p>{{ trade.fibonacci_retracement }}</p>
            </div>
            <div class="analysis-section">
                <p><strong>SMC Trading:</strong></p>
                <p>{{ trade.smc_trading }}</p>
            </div>
        </div>
        <div class="fundamental-analysis">
            <h3><strong>Fundamental Analysis:</strong></h3>
            <p>{{ trade.fundamental_analysis }}</p>
        </div>
    </div>
    </div>
    <div class="containerimage">
        <h2>Screen Shots</h2>
        <div class="section">
           
            {% if trade.entry_trade_image %}
        <p><strong>Entry Trade Image:</strong><br><img src="{{ trade.entry_trade_image.url }}" alt="Entry Trade Image" width="500"></p>
    {% endif %}
        </div>
        <div class="section">
            
                            {% if trade.exit_trade_image %}
        <p><strong>Exit Trade Image:</strong><br><img src="{{ trade.exit_trade_image.url }}" alt="Exit Trade Image" width="500"></p>
    {% endif %}
           
        </div>
        <div class="section">
            
            {% if trade.technical_analysis_image %}
        <p><strong>Technical Analysis Image:</strong><br><img src="{{ trade.technical_analysis_image.url }}" alt="Technical Analysis Image" width="500"></p>
    {% endif %}
        </div>
    </div>

<div class="containertext">
    <h2>Mistakes</h2>
    <ul>
        {% for mistake in trade.mistakes %}
            <li>{{ mistake }}</li>
        {% endfor %}
    </ul>

    <h2>Lessons Learned</h2>
    <ul>
        {% for lesson in trade.lessons %}
            <li>{{ lesson }}</li>
        {% endfor %}
    </ul>

    <h2>Additional</h2>
    <ul>
        {% for additional in trade.additional %}
            <li>{{ additional }}</li>
        {% endfor %}
    </ul>
</div>

<div class="">
    <a href="{% url 'trade_list' %}">Back to Trade List</a>

    <a href="{% url 'edit_trade' trade.pk %}">Edit Trade</a>
    <a href="{% url 'delete_trade' trade.pk %}">Delete Trade</a>
    <a href="{% url 'trade_list' %}">Back to Trade List</a>
</div>
</body>
</html>

trades/templates/trade_list.html
<!-- trades/templates/trade_list.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Trade List</title>
</head>
<body>
    <h1>Trade List</h1>
    <a href="{% url 'add_trade' %}">Add New Trade</a>
  



    <ul>
        {% for trade in trades %}
            <li><a href="{% url 'trade_detail' trade.id %}">{{ trade }}</li>
        {% endfor %}
    </ul>
</body>
</html>

trades/templates/trades/confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Confirm Delete</title>
</head>
<body>
    <h1>Are you sure you want to delete this trade?</h1>
    <p><strong>Trade:</strong> {{ trade }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
    </form>
    <a href="{% url 'trade_detail' trade.pk %}">Cancel</a>
</body>
</html>

trades/templates/trades/edit_trade.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Trade</title>
</head>
<body>
    <h1>Edit Trade</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    
</body>
</html>

trades/templates/trades/trade_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Trade Detail</title>
</head>
<body>
    <h1>Trade Detail</h1>
    <p><strong>Trade:</strong> {{ trade }}</p>
    <p><strong>Currency Fair:</strong> {{ trade.currency_fair }}</p>
    <!-- Display other details here -->
    <a href="{% url 'edit_trade' trade.pk %}">Edit Trade</a>
    <a href="{% url 'delete_trade' trade.pk %}">Delete Trade</a>
    <a href="{% url 'trade_list' %}">Back to Trade List</a>
</body>
</html>